# Generated by Django 3.0.11 on 2021-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('on_progress', 'On Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=30, verbose_name='Status'),
        ),
    ]
