# Generated by Django 3.0.11 on 2021-01-07 15:08

from django.db import migrations, models
import django.utils.timezone
import django_multitenant.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Employee Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=255, verbose_name='Employee Name')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
